### ISSUE TITLE
Openssl support for linux (compile.sh) ?

### ISSUE THREAD

**Issue by dausruddin** [iTXTech/php-build-scripts#13]
I saw the commit for openssl on windows script, but not on compile.sh
I have been trying to build using compile.sh on my debian 3 times, but all doesnt support openssl. Mind to adjust the script to include openssl? Im not good at it, so I will waiting for you to make it. Thank you :)

**Comment by ishitatsuyuki** [comment]
No, download PHP source, configure and make install. A new script may be released in a few days.

**Comment by dausruddin** [comment]
`./configure --with-openssl` is enough? No need to include other options?

**Comment by ishitatsuyuki** [comment]
No, many are needed. Consider using the script as a reference, or wait the new script to be added.

**Comment by dausruddin** [comment]
I guess, I need to wait for a new script then. I couldnt understand the script much. Thank you.
