### ISSUE TITLE
Thanks Jenkins.sh...

### ISSUE THREAD

**Issue by xpyctum** [iTXTech/php-build-scripts#14]
Really thanks. Jenkins.sh is broken my server. 
Apache, MySQL,and all server apps broken because script use rm -rf 
Thanks.

**Comment by ishitatsuyuki** [comment]
we don't support old branch. it's on the plan for removal.

**Comment by xpyctum** [comment]
But you send me here from faq. 
![image](https://cloud.githubusercontent.com/assets/6584811/17763983/d7a16512-6535-11e6-9a66-e55d21f15ffa.png)

**Comment by ishitatsuyuki** [comment]
Why you even had an idea to touch jenkins? Also, take risk if you ran it as root.

**Comment by xpyctum** [comment]
because it wrote in README.md

**Comment by ishitatsuyuki** [comment]
Again, if you ran it as root, it's up to your responsibility. Inspect the content before you run a file. These script are provided by best effort basis.

**Comment by xpyctum** [comment]
But you need check your script.

**Comment by ishitatsuyuki** [comment]
This is not for your use. You don't read the words. This is used for previous Jenkins only and put there for a reference.
