### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Nicolas-PL** [iTXTech/php-build-scripts#18]
Hello !

I have this error : 

Curl/TAR/gcc are installed.

`## ----------- ##
## -----------

configure:3234: checking for grep that handles long lines and -e
configure:3292: result: /bin/grep
configure:3297: checking for egrep
configure:3359: result: /bin/grep -E
configure:3364: checking for a sed that does not truncate output
configure:3418: result: /bin/sed
configure:3528: checking build system type
configure:3542: result: i686-pc-linux-gnu
configure:3562: checking host system type
configure:3575: result: i686-pc-linux-gnu
configure:3595: checking target system type
configure:3608: result: i686-pc-linux-gnu
configure:3783: checking for cc
configure:3799: found /usr/bin/cc
configure:3810: result: cc
configure:3841: checking for C compiler version
configure:3850: cc --version >&5
cc (Debian 4.7.2-5) 4.7.2
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:3861: $? = 0
configure:3850: cc -v >&5
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/i486-linux-gnu/4.7/lto-wrapper
Target: i486-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 4.7.2-5' --with-bugurl=file:///usr/share/doc/gcc-4.7/README.Bugs --enable-languages=c,c++,go,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.7 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.7 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --enable-targets=all --with-arch-32=i586 --with-tune=generic --enable-checking=release --build=i486-linux-gnu --host=i486-linux-gnu --target=i486-linux-gnu
Thread model: posix
gcc version 4.7.2 (Debian 4.7.2-5) 
configure:3861: $? = 0
configure:3850: cc -V >&5
cc: error: unrecognized command line option '-V'
cc: fatal error: no input files
compilation terminated.
configure:3861: $? = 4
configure:3850: cc -q version >&5
cc: error: unrecognized command line option '-qversion'
cc: fatal error: no input files
compilation terminated.
configure:3861: $? = 4
configure:3881: checking whether the C compiler works
configure:3903: cc    conftest.c  >&5
/usr/bin/ld: /usr/lib/gcc/i486-linux-gnu/4.7/../../../i386-linux-gnu/crti.o: unrecognized relocation (0x2b) in section `.init'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
configure:3907: $? = 1
configure:3945: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:3950: error: in`/home/srv4-hmserv.eu-19134/work':
configure:3952: error: C compiler cannot create executables
See `config.log' for more details

`

Thanks !

**Comment by ishitatsuyuki** [comment]
Your compiler is broken, please install all the required dependency and update the system.

**Comment by Nicolas-PL** [comment]
Hi,

also need perl gcc make automake libtool autoconf m4 g++ ;)

**Comment by ishitatsuyuki** [comment]
build-essential, we assume you have those installed.
