### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by alex2534alex** [iTXTech/php-build-scripts#23]
I have built PHP binary for Linux by your scripts.
1. I have some discomfort with the console. When I type command appears "Genisys>" line. [Screenshot](https://cloud.githubusercontent.com/assets/15706847/18224181/ff530654-71d5-11e6-9a8b-98f5fa616aa6.png)
2. Now CTRL+C causes force stoping. But after server restart, RakLib works fine. Previously, it was the equivalent of the "stop" command.
3. Not sure that it matters, but after stopping said "zend_mm_heap corrupted"

**Comment by alex2534alex** [comment]
UPD: "zend_mm_heap corrupted" appears very often, after "stop" command or later. After that forcibly stops the server without unloading plugins/levels/threads

**Comment by alex2534alex** [comment]
@ishitatsuyuki , someone, help((

**Comment by ishitatsuyuki** [comment]
I'm glad to help banning you for not following the rules.
