### ISSUE TITLE
Not work Linux

### ISSUE THREAD

**Issue by Erkam246** [iTXTech/php-build-scripts#26]
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for cc... no
checking for gcc... no
configure: error: in `/root/php-build-scripts-master/work':
configure: error: no acceptable C compiler found in $PATH
See`config.log' for more details

**Comment by ishitatsuyuki** [comment]
Yes, it won't work for idiots.

> You need **basic compiler package group**, build dependencies and ...
