### ISSUE TITLE
Other error

### ISSUE THREAD

**Issue by Erkam246** [iTXTech/php-build-scripts#27]
root@vps:~/php-build-scripts-master# ./linux-build-install.sh
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for cc... no
checking for gcc... no
configure: error: in `/root/php-build-scripts-master/work':
configure: error: no acceptable C compiler found in $PATH
See`config.log' for more details

Pls help

**Comment by ishitatsuyuki** [comment]
**You need basic compiler package group**
Ask questions on chat. You will get banned next time.

http://www.youareanidiot.org/

**Comment by Erkam246** [comment]
oh ok
