### ISSUE TITLE
Unable to compile php7

### ISSUE THREAD

**Issue by yanaex** [iTXTech/php-build-scripts#28]
ext/iconv/.libs/iconv.o: In function `php_iconv_stream_filter_dtor':
/root/Genisys/php-build-scripts/work/ext/iconv/iconv.c:2557: undefined reference to`libiconv_close'
ext/iconv/.libs/iconv.o: In function `_php_iconv_strlen':
/root/Genisys/php-build-scripts/work/ext/iconv/iconv.c:755: undefined reference to`libiconv_open'
/root/Genisys/php-build-scripts/work/ext/iconv/iconv.c:779: undefined reference to `libiconv'
/root/Genisys/php-build-scripts/work/ext/iconv/iconv.c:813: undefined reference to`libiconv_close'
ext/iconv/.libs/iconv.o: In function `_php_iconv_appendl':
/root/Genisys/php-build-scripts/work/ext/iconv/iconv.c:474: undefined reference to`libiconv'
/root/Genisys/php-build-scripts/work/ext/iconv/iconv.c:508: undefined reference to `libiconv'
ext/iconv/.libs/iconv.o: In function`_php_iconv_mime_decode':
/root/Genisys/php-build-scripts/work/ext/iconv/iconv.c:1505: undefined reference to `libiconv_open'
/root/Genisys/php-build-scripts/work/ext/iconv/iconv.c:1998: undefined reference to`libiconv_close'
/root/Genisys/php-build-scripts/work/ext/iconv/iconv.c:2001: undefined reference to `libiconv_close'
/root/Genisys/php-build-scripts/work/ext/iconv/iconv.c:1616: undefined reference to`libiconv_close'
/root/Genisys/php-build-scripts/work/ext/iconv/iconv.c:1619: undefined reference to `libiconv_open'
ext/iconv/.libs/iconv.o: In function`_php_iconv_substr':
/root/Genisys/php-build-scripts/work/ext/iconv/iconv.c:876: undefined reference to `libiconv_open'
/root/Genisys/php-build-scripts/work/ext/iconv/iconv.c:900: undefined reference to`libiconv'
/root/Genisys/php-build-scripts/work/ext/iconv/iconv.c:955: undefined reference to `libiconv_close'
/root/Genisys/php-build-scripts/work/ext/iconv/iconv.c:959: undefined reference to`libiconv_close'
/root/Genisys/php-build-scripts/work/ext/iconv/iconv.c:908: undefined reference to `libiconv_open'
ext/iconv/.libs/iconv.o: In function`_php_iconv_mime_encode':
/root/Genisys/php-build-scripts/work/ext/iconv/iconv.c:1194: undefined reference to `libiconv_open'
/root/Genisys/php-build-scripts/work/ext/iconv/iconv.c:1208: undefined reference to`libiconv_open'
/root/Genisys/php-build-scripts/work/ext/iconv/iconv.c:1326: undefined reference to `libiconv'
/root/Genisys/php-build-scripts/work/ext/iconv/iconv.c:1278: undefined reference to`libiconv'
/root/Genisys/php-build-scripts/work/ext/iconv/iconv.c:1310: undefined reference to `libiconv'
/root/Genisys/php-build-scripts/work/ext/iconv/iconv.c:1470: undefined reference to`libiconv_close'
/root/Genisys/php-build-scripts/work/ext/iconv/iconv.c:1379: undefined reference to `libiconv'
/root/Genisys/php-build-scripts/work/ext/iconv/iconv.c:1411: undefined reference to`libiconv'
/root/Genisys/php-build-scripts/work/ext/iconv/iconv.c:1467: undefined reference to `libiconv_close'
/root/Genisys/php-build-scripts/work/ext/iconv/iconv.c:1454: undefined reference to`libiconv'
ext/iconv/.libs/iconv.o: In function `php_iconv_string':
/root/Genisys/php-build-scripts/work/ext/iconv/iconv.c:578: undefined reference to`libiconv_open'
/root/Genisys/php-build-scripts/work/ext/iconv/iconv.c:590: undefined reference to `libiconv'
/root/Genisys/php-build-scripts/work/ext/iconv/iconv.c:608: undefined reference to`libiconv'
/root/Genisys/php-build-scripts/work/ext/iconv/iconv.c:618: undefined reference to `libiconv_close'
ext/iconv/.libs/iconv.o: In function`_php_iconv_strpos':
/root/Genisys/php-build-scripts/work/ext/iconv/iconv.c:1003: undefined reference to `libiconv_open'
/root/Genisys/php-build-scripts/work/ext/iconv/iconv.c:1031: undefined reference to`libiconv'
/root/Genisys/php-build-scripts/work/ext/iconv/iconv.c:1145: undefined reference to `libiconv_close'
ext/iconv/.libs/iconv.o: In function`php_iconv_stream_filter_append_bucket':
/root/Genisys/php-build-scripts/work/ext/iconv/iconv.c:2708: undefined reference to `libiconv'
/root/Genisys/php-build-scripts/work/ext/iconv/iconv.c:2707: undefined reference to`libiconv'
/root/Genisys/php-build-scripts/work/ext/iconv/iconv.c:2629: undefined reference to `libiconv'
ext/iconv/.libs/iconv.o: In function`php_iconv_stream_filter_ctor':
/root/Genisys/php-build-scripts/work/ext/iconv/iconv.c:2583: undefined reference to `libiconv_open'
collect2: ld returned 1 exit status
make: **\* [sapi/cli/php] Error 1

**Comment by ishitatsuyuki** [comment]
**We don't support for polluted environment.**
