### ISSUE TITLE
It dont work at all !!!!!!

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [iTXTech/php-build-scripts#29]
CRITICAL] Unable to find the pthreads extension.
[CRITICAL] Please use the installer provided on the homepage.

Really? And dont call me a idiot ! I did exactly how i was told on readme!
So why wont work :( !

(Ik is pthtreads)

**Comment by ishitatsuyuki** [comment]
Idiot!
Easy, you are not removing your installation in your prefix.
