### ISSUE TITLE
Base address marks unusable memory region

### ISSUE THREAD

**Issue by MHIGists** [iTXTech/php-build-scripts#32]
Hi It's me again...Please add `opcache.mmap_base = 0x20000000` to get rid of the `Base address marks unusable memory region` errors. Unfortunately I do not know the significance of the value `0x20000000`. I can only tell you that this value works to solve the problem (Tried and tested). Can't create PR right now

**Comment by dktapps** [comment]
https://github.com/iTXTech/Genisys/blob/master/src/pocketmine/PocketMine.php#L462

**Comment by MHIGists** [comment]
Hmm interesting then why `Base adress` errors are occurring if  `opcache.mmap_base` is not specified...
Errors are showing up saying that the opcache.mmap_base  is not specified so I guess it has to be in the php.ini itself. Because  it's only a guess but, when the server starts it loads first all the php runtime configurations and then the ines specified in PocketMine-MP which ends in being ignored because some configs cannot be changed when server is already running.
